# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaNuevaReserva.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textFecInicial = QtWidgets.QTextEdit(self.centralwidget)
        self.textFecInicial.setGeometry(QtCore.QRect(249, 32, 116, 22))
        self.textFecInicial.setObjectName("textFecInicial")
        self.textFecFinal = QtWidgets.QTextEdit(self.centralwidget)
        self.textFecFinal.setGeometry(QtCore.QRect(629, 32, 116, 22))
        self.textFecFinal.setObjectName("textFecFinal")
        self.textLitros = QtWidgets.QTextEdit(self.centralwidget)
        self.textLitros.setGeometry(QtCore.QRect(629, 78, 116, 22))
        self.textLitros.setObjectName("textLitros")
        self.textCodReserva = QtWidgets.QTextEdit(self.centralwidget)
        self.textCodReserva.setGeometry(QtCore.QRect(249, 78, 116, 22))
        self.textCodReserva.setObjectName("textCodReserva")
        self.labelFechaInicial = QtWidgets.QLabel(self.centralwidget)
        self.labelFechaInicial.setGeometry(QtCore.QRect(45, 35, 192, 16))
        self.labelFechaInicial.setObjectName("labelFechaInicial")
        self.labelFechaFinal = QtWidgets.QLabel(self.centralwidget)
        self.labelFechaFinal.setGeometry(QtCore.QRect(438, 35, 179, 16))
        self.labelFechaFinal.setObjectName("labelFechaFinal")
        self.labelLitros = QtWidgets.QLabel(self.centralwidget)
        self.labelLitros.setGeometry(QtCore.QRect(438, 81, 152, 16))
        self.labelLitros.setObjectName("labelLitros")
        self.labelCodigoReserva = QtWidgets.QLabel(self.centralwidget)
        self.labelCodigoReserva.setGeometry(QtCore.QRect(45, 81, 167, 16))
        self.labelCodigoReserva.setObjectName("labelCodigoReserva")
        self.comboBox_Coches = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Coches.setGeometry(QtCore.QRect(320, 180, 421, 20))
        self.comboBox_Coches.setObjectName("comboBox_Coches")
        self.comboBox_Clientes = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Clientes.setGeometry(QtCore.QRect(50, 180, 196, 20))
        self.comboBox_Clientes.setObjectName("comboBox_Clientes")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 340, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelFechaInicial.setText(_translate("MainWindow", "Fecha Inicial (DD/MM/AAAA):"))
        self.labelFechaFinal.setText(_translate("MainWindow", "Fecha Final (DD/MM/AAAA):"))
        self.labelLitros.setText(_translate("MainWindow", "Litros Consumidos:"))
        self.labelCodigoReserva.setText(_translate("MainWindow", "Código Reserva:"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
