# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaInicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnNuevaReserva = QtWidgets.QPushButton(self.centralwidget)
        self.btnNuevaReserva.setGeometry(QtCore.QRect(40, 30, 110, 40))
        self.btnNuevaReserva.setObjectName("btnNuevaReserva")
        self.btnListadoReservas = QtWidgets.QPushButton(self.centralwidget)
        self.btnListadoReservas.setGeometry(QtCore.QRect(250, 30, 110, 40))
        self.btnListadoReservas.setObjectName("btnListadoReservas")
        self.btnClienteMes = QtWidgets.QPushButton(self.centralwidget)
        self.btnClienteMes.setGeometry(QtCore.QRect(40, 150, 110, 40))
        self.btnClienteMes.setObjectName("btnClienteMes")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(250, 150, 110, 40))
        self.btnSalir.setObjectName("btnSalir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNuevaReserva.setText(_translate("MainWindow", "Nueva Reserva"))
        self.btnListadoReservas.setText(_translate("MainWindow", "Listado Reservas"))
        self.btnClienteMes.setText(_translate("MainWindow", "Cliente Mes"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
