# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaClientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql
from PyQt5 import QtCore, QtGui, QtWidgets


class Clientes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditNif = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNif.setGeometry(QtCore.QRect(200, 30, 113, 22))
        self.lineEditNif.setObjectName("lineEdit")
        self.lineEditNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNombre.setGeometry(QtCore.QRect(200, 80, 111, 22))
        self.lineEditNombre.setObjectName("lineEdit_2")
        self.labelNif = QtWidgets.QLabel(self.centralwidget)
        self.labelNif.setGeometry(QtCore.QRect(60, 30, 55, 16))
        self.labelNif.setObjectName("label")
        self.labelNombre = QtWidgets.QLabel(self.centralwidget)
        self.labelNombre.setGeometry(QtCore.QRect(60, 80, 55, 16))
        self.labelNombre.setObjectName("label_2")
        self.labelPrimerApellido = QtWidgets.QLabel(self.centralwidget)
        self.labelPrimerApellido.setGeometry(QtCore.QRect(60, 130, 91, 16))
        self.labelPrimerApellido.setObjectName("label_3")
        self.labelSegundoApellido = QtWidgets.QLabel(self.centralwidget)
        self.labelSegundoApellido.setGeometry(QtCore.QRect(60, 180, 111, 16))
        self.labelSegundoApellido.setObjectName("label_4")
        self.labelCalle = QtWidgets.QLabel(self.centralwidget)
        self.labelCalle.setGeometry(QtCore.QRect(60, 230, 55, 16))
        self.labelCalle.setObjectName("label_5")
        self.labelNumero = QtWidgets.QLabel(self.centralwidget)
        self.labelNumero.setGeometry(QtCore.QRect(60, 280, 55, 16))
        self.labelNumero.setObjectName("label_6")
        self.labelMunicipio = QtWidgets.QLabel(self.centralwidget)
        self.labelMunicipio.setGeometry(QtCore.QRect(60, 330, 55, 16))
        self.labelMunicipio.setObjectName("label_7")
        self.labelTelefono = QtWidgets.QLabel(self.centralwidget)
        self.labelTelefono.setGeometry(QtCore.QRect(60, 380, 55, 16))
        self.labelTelefono.setObjectName("label_8")
        self.lineEditPrimerApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPrimerApellido.setGeometry(QtCore.QRect(200, 130, 113, 22))
        self.lineEditPrimerApellido.setObjectName("lineEdit_3")
        self.lineEditSegundoApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSegundoApellido.setGeometry(QtCore.QRect(200, 180, 113, 22))
        self.lineEditSegundoApellido.setObjectName("lineEdit_4")
        self.lineEditCalle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCalle.setGeometry(QtCore.QRect(200, 220, 113, 22))
        self.lineEditCalle.setObjectName("lineEdit_5")
        self.lineEditNumero = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero.setGeometry(QtCore.QRect(200, 280, 113, 22))
        self.lineEditNumero.setObjectName("lineEdit_6")
        self.lineEditMunicipio = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMunicipio.setGeometry(QtCore.QRect(200, 330, 113, 22))
        self.lineEditMunicipio.setObjectName("lineEdit_7")
        self.lineEditTelefono = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTelefono.setGeometry(QtCore.QRect(200, 380, 113, 22))
        self.lineEditTelefono.setObjectName("lineEdit_8")
        self.btnNuevo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNuevo.setGeometry(QtCore.QRect(500, 80, 93, 28))
        self.btnNuevo.setObjectName("pushButton")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(500, 160, 93, 28))
        self.btnBuscar.setObjectName("pushButton_2")
        self.btnModificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnModificar.setGeometry(QtCore.QRect(500, 240, 131, 28))
        self.btnModificar.setObjectName("pushButton_3")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(500, 310, 131, 28))
        self.btnEliminar.setObjectName("pushButton_4")
        self.btnOk = QtWidgets.QPushButton(self.centralwidget)
        self.btnOk.setGeometry(QtCore.QRect(200, 480, 93, 28))
        self.btnOk.setObjectName("pushButton_5")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(460, 480, 93, 28))
        self.btnCancel.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnNuevo.clicked.connect(self.ejecutarFuncionesNuevo)
        self.btnBuscar.clicked.connect(self.buscarClienteBD)
        self.btnCancel.clicked.connect(lambda: self.ejecutarFunciones(MainWindow))


    def ejecutarFuncionesNuevo(self):
        self.capturarDatos()
        self.insertarClienteBD()
        self.limpiarCampos()

    def ejecutarFunciones(self, MainWindow):
        self.mostrarInicio()
        MainWindow.close()

    def mostrarInicio(self):
        from ventanaInicio import Inicio
        self.ventanaInicio = QtWidgets.QMainWindow()
        self.inicio = Inicio()
        self.inicio.setupUi(self.ventanaInicio)
        self.ventanaInicio.show()
        
    def capturarDatos(self):
        self.nif = self.lineEditNif.text()
        self.nombre = self.lineEditNombre.text()
        self.primerApellido = self.lineEditPrimerApellido.text()
        self.segundoApellido = self.lineEditSegundoApellido.text()
        self.calle = self.lineEditCalle.text()
        self.numero = self.lineEditNumero.text()
        self.municipio = self.lineEditMunicipio.text()
        self.telefono = self.lineEditTelefono.text()

        self.nombreCompleto = self.nombre+(" ")+self.primerApellido+(" ")+self.segundoApellido
        self.direccion = self.calle+(",")+self.numero+(",")+self.municipio
        self.telefonoInt = int(self.telefono)

    def limpiarCampos(self):
        self.lineEditNif.clear()
        self.lineEditNombre.clear()
        self.lineEditPrimerApellido.clear()
        self.lineEditSegundoApellido.clear()
        self.lineEditCalle.clear()
        self.lineEditNumero.clear()
        self.lineEditMunicipio.clear()
        self.lineEditTelefono.clear()


    def insertarClienteBD(self):
        conexion = mysql.connector.connect(
            host='localhost',
            port=3306,
            user='root',
            password='castelao',
            db='UD02BDReservaCoches')
        cur = conexion.cursor()
        sql = "INSERT INTO clientes (clNif, clNombre, clDireccion, clTelefono) VALUES ('{}', '{}', '{}', '{)'".format(
            self.nif, self.nombreCompleto, self.direccion, self.telefonoInt)
            # val = (self.codigoReservaInt, self.fechaInicialDate, self.fechaFinalDate)
        cur.execute(sql)

        conexion.commit()
        print(cur.rowcount, "registro insertado")

        conexion.close()


    def buscarClienteBD(self, id):
        conexion = mysql.connector.connect(
            host='localhost',
            port=3306,
            user='root',
            password='castelao',
            db='UD02BDReservaCoches')
        cur = conexion.cursor()
        sql="select * from clientes where clNif = %s"
        nif= self.lineEditNif.text()
        cur.execute(sql, nif)
        result = cur.fetchall()
        for x in result:
            nombre = x[1]
            direccion = x[2]
            telefono = x[3]

        separador = ','
        nombreCompleto = nombre.split(separador)
        direccionCompleta = direccion.split(separador)

        self.lineEditNombre.setText(nombreCompleto[0])
        self.lineEditPrimerApellido.setText(nombreCompleto[1])
        self.lineEditSegundoApellido.setText(nombreCompleto[2])
        self.lineEditCalle.setText(direccionCompleta[0])
        self.lineEditNumero.setText(direccionCompleta[1])
        self.lineEditMunicipio.setText(direccionCompleta[2])
        self.lineEditTelefono.setText(telefono)

        self.lineEditNombre.setEnabled(False)
        self.lineEditPrimerApellido.setEnabled(False)
        self.lineEditSegundoApellido.setEnabled(False)
        self.lineEditCalle.setEnabled(False)
        self.lineEditNumero.setEnabled(False)
        self.lineEditMunicipio.setEnabled(False)
        self.lineEditTelefono.setEnabled(False)

    def modificarCliente(self, id):
        self.lineEditNombre.setEnabled(True)
        self.lineEditPrimerApellido.setEnabled(True)
        self.lineEditSegundoApellido.setEnabled(True)
        self.lineEditCalle.setEnabled(True)
        self.lineEditNumero.setEnabled(True)
        self.lineEditMunicipio.setEnabled(True)
        self.lineEditTelefono.setEnabled(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clientes"))
        self.labelNif.setText(_translate("MainWindow", "NIF"))
        self.labelNombre.setText(_translate("MainWindow", "Nombre"))
        self.labelPrimerApellido.setText(_translate("MainWindow", "Primer apellido"))
        self.labelSegundoApellido.setText(_translate("MainWindow", "Segundo apellido"))
        self.labelCalle.setText(_translate("MainWindow", "Calle"))
        self.labelNumero.setText(_translate("MainWindow", "Número"))
        self.labelMunicipio.setText(_translate("MainWindow", "Municipio"))
        self.labelTelefono.setText(_translate("MainWindow", "Teléfono"))
        self.btnNuevo.setText(_translate("MainWindow", "Nuevo Cliente"))
        self.btnBuscar.setText(_translate("MainWindow", "Buscar Cliente"))
        self.btnModificar.setText(_translate("MainWindow", "Modificar Cliente"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar Cliente"))
        self.btnOk.setText(_translate("MainWindow", "OK"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Clientes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
